name: bl-image-indexer
channels:
- defaults
dependencies:
- certifi=2016.2.28=py27_0
- openssl=1.0.2l=0
- pip=9.0.1=py27_1
- python=2.7.13=0
- readline=6.2=2
- setuptools=36.4.0=py27_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- pip:
  - backports.weakref==1.0.post1
  - bleach==1.5.0
  - boto3==1.4.7
  - botocore==1.7.34
  - docutils==0.14
  - funcsigs==1.0.2
  - futures==3.1.1
  - html5lib==0.9999999
  - jmespath==0.9.3
  - markdown==2.6.9
  - mock==2.0.0
  - numpy==1.13.3
  - pbr==3.1.1
  - protobuf==3.4.0
  - python-dateutil==2.6.1
  - s3transfer==0.1.11
  - six==1.11.0
  - tensorflow==1.3.0
  - tensorflow-tensorboard==0.1.8
  - werkzeug==0.12.2
prefix: /home/bluehack/anaconda3/envs/bl-image-indexer

